model_parameters:
  onnx_model: 'yolov5m_relu.onnx'
  march: 'bernoulli2'
  output_model_file_prefix: '320x320_nv12'
  working_dir: 'tmp/yolov5m_relu'
  layer_out_dump: False
  log_level: 'debug'

input_parameters:
  input_name: ""

  input_type_rt: 'nv12'

  input_type_train: 'rgb'

  input_layout_train: 'NCHW'

  input_shape: ''

  input_batch: 1

  norm_type: 'data_scale'

  mean_value: ''

  scale_value: 0.003921568627451

calibration_parameters:
  cal_data_dir: './calibration_data_rgb_f32'

  preprocess_on: False

  calibration_type: 'default'

compiler_parameters:
  compile_mode: 'latency'

  debug: False

  core_num: 2

  optimize_level: 'O3'
